# https://argo-cd.readthedocs.io/en/release-1.8/operator-manual/declarative-setup/#applications
# https://argo-cd.readthedocs.io/en/release-1.8/user-guide/auto_sync/#automatic-pruning
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AntoineLemarchand/alemarch_InceptionOfThings
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

