Vagrant.configure("2") do |config|

  config.vm.provider "libvirt" do |lv|
    lv.cpus = 2
    lv.memory = 1024
  end
  config.vm.synced_folder "./confs", "/confs", type:"rsync"
  config.vm.synced_folder "./scripts", "/scripts", type:"rsync"
  config.vm.box = "generic/alpine317"

  config.vm.define "Server" do |server|
    server.vm.hostname = "alemarchS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", privileged: true, path: 'scripts/server.sh'
  end
end
