Vagrant.configure("2") do |config|

  config.vm.define "Server" do |server|
    server.vm.box = "generic/alpine38"
    server.vm.hostname = "alemarchS"
    server.vm.network "private_network", ip: "192.168.56.110"
  end

  config.vm.define "ServiceWorker" do |serviceWorker|
    serviceWorker.vm.box = "generic/alpine38"
    serviceWorker.vm.hostname = "alemarchSW"
    serviceWorker.vm.network "private_network", ip: "192.168.56.111"
  end

end
